# Generated by Django 4.1.3 on 2022-11-15 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("aaronapp", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="TT",
            new_name="AA",
        ),
    ]
