# Generated by Django 4.1.3 on 2022-11-16 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("aaronapp", "0002_rename_tt_aa"),
    ]

    operations = [
        migrations.RenameField(
            model_name="aa",
            old_name="age",
            new_name="input",
        ),
        migrations.RenameField(
            model_name="aa",
            old_name="name",
            new_name="user_ID",
        ),
    ]
