# Generated by Django 4.1.3 on 2022-11-16 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("aaronapp", "0003_rename_age_aa_input_rename_name_aa_user_id"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="AA",
            new_name="Data",
        ),
    ]
